apiVersion: automation.cloudbees.io/v1alpha1
kind: action
name: scan
description: "Scan using multiple plugins"

outputs:
  #Code Scan related Outputs
  account_credentials:
    value: ${{ steps.plan.outputs.account_credentials}}
    description: "Account credentials"
  github-inventory:
    value: ${{ steps.plan.outputs.github-inventory}}
    description: "Github inventory"
  github-decorator:
    value: ${{ steps.plan.outputs.github-decorator}}
    description: "Github decorator"
  bitbucket-inventory:
    value: ${{ steps.plan.outputs.bitbucket-inventory}}
    description: "Bitbucket inventory"
  bitbucket-decorator:
    value: ${{ steps.plan.outputs.bitbucket-decorator}}
    description: "Bitbucket decorator"
  gerrit-inventory:
    value: ${{ steps.plan.outputs.gerrit-inventory}}
    description: "Gerrit inventory"
  gerrit-decorator:
    value: ${{ steps.plan.outputs.gerrit-decorator}}
    description: "Gerrit decorator"
  gitlab-inventory:
    value: ${{ steps.plan.outputs.gitlab-inventory}}
    description: "Gitlab inventory"
  gitlab-decorator:
    value: ${{ steps.plan.outputs.gitlab-decorator}}
    description: "Gitlab decorator"
  scc:
    value: ${{ steps.plan.outputs.scc}}
    description: "SCC Scanner"
  gosec:
    value: ${{ steps.plan.outputs.gosec}}
    description: "Gosec"
  njsscan:
    value: ${{ steps.plan.outputs.njsscan}}
    description: "NJS"
  gitleaks:
    value: ${{ steps.plan.outputs.gitleaks}}
    description: "Gitleaks"
  sonar-props:
    value: ${{ steps.plan.outputs.sonar-props}}
    description: "SonarQube"
  sonar:
    value: ${{ steps.plan.outputs.sonar}}
    description: "SonarQube Scanner"
  blackduck-props:
    value: ${{ steps.plan.outputs.blackduck-props}}
    description: "BlackDuck"
  blackduck:
    value: ${{ steps.plan.outputs.blackduck}}
    description: "BlackDuck Scanner"
  coverity-props:
    value: ${{ steps.plan.outputs.coverity-props}}
    description: "Coverity"
  coverity:
    value: ${{ steps.plan.outputs.coverity}}
    description: "Coverity Polaris"
  checkov:
    value: ${{ steps.plan.outputs.checkov}}
    description: "Checkov"
  klocwork-props:
    value: ${{ steps.plan.outputs.klocwork-props}}
    description: "Klocwork"
  klocwork:
    value: ${{ steps.plan.outputs.klocwork}}
    description: "Klocwork Scanner"
  snyk-sast-props:
    value: ${{ steps.plan.outputs.snyk-sast-props}}
    description: "Snyk SAST"
  snyk-sast:
    value: ${{ steps.plan.outputs.snyk-sast}}
    description: "Snyk SAST Scanner"
  
  #Binary Scan related Outputs
  wf_artifact_token:
    value: ${{ steps.plan.outputs.wf_artifact_token }}
    description: "Workflow artifact token"
  wf_artifact_component_id:
    value: ${{ steps.plan.outputs.wf_artifact_component_id }}
    description: "Workflow artifact component id"
  wfartifact-inventory:
    value: ${{ steps.plan.outputs.wfartifact-inventory}}
    description: "Workflow artifact inventory"
  wfartifact-decorator:
    value: ${{ steps.plan.outputs.wfartifact-decorator}}
    description: "Workflow artifact decorator"
  ecr-inventory:
    value: ${{ steps.plan.outputs.ecr-inventory}}
    description: "ECR inventory"
  ecr-metadata:
    value: ${{ steps.plan.outputs.ecr-metadata}}
    description: "ECR metadata"
  ecr_role_arn:
    value: ${{ steps.plan.outputs.ecr_role_arn}}
    description: "ECR Role ARN"
  ecr_region_name:
    value: ${{ steps.plan.outputs.ecr_region_name}}
    description: "ECR Region Name"
  jfrog-inventory:
    value: ${{ steps.plan.outputs.jfrog-inventory}}
    description: "JFrog Artifactory Inventory"
  jfrog-metadata:
    value: ${{ steps.plan.outputs.jfrog-metadata}}
    description: "JFrog Artifactory Metadata"
  jfrog_token:
    value: ${{ steps.plan.outputs.jfrog_token}}
    description: "JFrog Artifactory Token"
  trivy:
    value: ${{ steps.plan.outputs.trivy}}
    description: "Trivy"
  findsecbugs:
    value: ${{ steps.plan.outputs.findsecbugs}}
    description: "FindSecBugs"
  syft:
    value: ${{ steps.plan.outputs.syft}}
    description: "Syft SBOM"
  grype:
    value: ${{ steps.plan.outputs.grype}}
    description: "Grype"

runs:
  using: composite
  steps:
    - name: Initiate execution plan
      uses: docker://020229604682.dkr.ecr.us-east-1.amazonaws.com/actions/assets-plugin-chain-utils:latest
      id: plan
      with:
        entrypoint: assets-plugin-chain-utils
        args: configure
      env:
        INPUT_CLOUDBEES_API_TOKEN: ${{ cloudbees.api.token }}
        INPUT_CLOUDBEES_API_URL: ${{ cloudbees.api.url }}
        INPUT_RUN_ID: ${{ cloudbees.run_id }}
        INPUT_INIT_OUTPUTS: 'wf_artifact_component_id,wf_artifact_token,ecr_role_arn,ecr_region_name,account_credentials,github-inventory,github-decorator,scc,bitbucket-inventory,bitbucket-decorator,gerrit-inventory,gerrit-decorator,gitlab-inventory,gitlab-decorator,gosec,njsscan,gitleaks,checkov,sonar-props,wfartifact-inventory,wfartifact-decorator,trivy,sonar,findsecbugs,syft,grype,blackduck,blackduck-props,coverity,coverity-props,klocwork,klocwork-props,snyk-sast,snyk-sast-props,ecr-inventory,ecr-metadata,jfrog-inventory,jfrog-metadata,jfrog_token'
