apiVersion: automation.cloudbees.io/v1alpha1
kind: action
name: scan
description: "Scan using multiple plugins"

outputs:
  #Code Scan related Outputs
  account_credentials:
    value: ${{ steps.plan.outputs.account_credentials}}
    description: "Account credentials"
  github-inventory:
    value: ${{ steps.plan.outputs.github-inventory}}
    description: "Github inventory"
  github-decorator:
    value: ${{ steps.plan.outputs.github-decorator}}
    description: "Github decorator"
  bitbucket-inventory:
    value: ${{ steps.plan.outputs.bitbucket-inventory}}
    description: "Bitbucket inventory"
  bitbucket-decorator:
    value: ${{ steps.plan.outputs.bitbucket-decorator}}
    description: "Bitbucket decorator"
  scc:
    value: ${{ steps.plan.outputs.scc}}
    description: "SCC Scanner"
  gosec:
    value: ${{ steps.plan.outputs.gosec}}
    description: "Gosec"
  njsscan:
    value: ${{ steps.plan.outputs.njsscan}}
    description: "NJS"
  gitleaks:
    value: ${{ steps.plan.outputs.gitleaks}}
    description: "Gitleaks"
  sonar-props:
    value: ${{ steps.plan.outputs.sonar-props}}
    description: "SonarQube"
  checkov:
    value: ${{ steps.plan.outputs.checkov}}
    description: "Checkov"
  
  #Binary Scan related Outputs
  wf_artifact_token:
    value: ${{ steps.set-outputs.outputs.wf_artifact_token}}
    description: "Workflow artifact token"
  wf_artifact_component_id:
    value: ${{ steps.set-outputs.outputs.wf_artifact_component_id}}
    description: "Workflow artifact component id"
  wfartifact-inventory:
    value: ${{ steps.plan.outputs.wfartifact-inventory}}
    description: "Workflow artifact inventory"
  wfartifact-decorator:
    value: ${{ steps.plan.outputs.wfartifact-decorator}}
    description: "Workflow artifact decorator"
  trivy:
    value: ${{ steps.plan.outputs.trivy}}
    description: "Trivy"
  findsecbugs:
    value: ${{ steps.plan.outputs.findsecbugs}}
    description: "FindSecBugs"
  syft:
    value: ${{ steps.plan.outputs.syft}}
    description: "Syft SBOM"
  grype:
    value: ${{ steps.plan.outputs.grype}}
    description: "Grype"

runs:
  using: composite
  steps:
    - name: Initiate execution plan
      uses: docker://020229604682.dkr.ecr.us-east-1.amazonaws.com/actions/assets-plugin-chain-utils:latest
      id: plan
      with:
        entrypoint: assets-plugin-chain-utils
        args: configure
      env:
        INPUT_CLOUDBEES_API_TOKEN: ${{ cloudbees.api.token }}
        INPUT_CLOUDBEES_API_URL: ${{ cloudbees.api.url }}
        INPUT_RUN_ID: ${{ cloudbees.run_id }}
        INPUT_PLUGIN_LIST: 'github-inventory,github-decorator,scc,bitbucket-inventory,bitbucket-decorator,gosec,njsscan,gitleaks,checkov,sonar,wfartifact-inventory,wfartifact-decorator,trivy,findsecbugs,syft,grype'
    
    - name: Set outputs conditionally
      uses: docker://alpine:3.18
      id: set-outputs
      run: |
        if [ -n "${{ steps.plan.outputs.wf_artifact_token }}" ]; then
          echo "${{ steps.plan.outputs.wf_artifact_token }}" > "$CLOUDBEES_OUTPUTS/wf_artifact_token"
        fi
        if [ -n "${{ steps.plan.outputs.wf_artifact_component_id }}" ]; then
           echo "${{ steps.plan.outputs.wf_artifact_component_id }}" > "$CLOUDBEES_OUTPUTS/wf_artifact_component_id"
        fi
      shell: bash
