apiVersion: automation.cloudbees.io/v1alpha1
kind: action
name: scan
description: "End scan chain"

runs:
  using: composite
  steps:
    - name: Complete execution plan
      uses: docker://020229604682.dkr.ecr.us-east-1.amazonaws.com/actions/assets-plugin-chain-utils:latest
      id: process-outputs
      with:
        entrypoint: assets-plugin-chain-utils
        args: process-outputs
      env:
        INPUT_CLOUDBEES_API_TOKEN: ${{ cloudbees.api.token }}
        INPUT_CLOUDBEES_API_URL: ${{ cloudbees.api.url }}
        INPUT_RUN_ID: ${{ cloudbees.run_id }}