apiVersion: automation.cloudbees.io/v1alpha1
kind: action
name: gitleaks-hybrid

inputs:
  ref:
    description: 'Flag to indicate the ref that should be archived (same as supplied to checkout)'
    required: false
    default: ''
  workspace-dir:
    description: 'Flag to mention the path where the checked out code will be present'
    required: false
    default: ''

runs:
  using: composite
  steps:
    - name: Generate sha and ref 
      uses: docker://020229604682.dkr.ecr.us-east-1.amazonaws.com/actions/assets-plugin-chain-utils:c7cbcb9a27d7f75effc0237ae78a96192402d81b
      with:
        entrypoint: assets-plugin-chain-utils
        args: get-commit-info
      env:
         INPUT_CLOUDBEES_API_TOKEN: ${{ cloudbees.api.token }}
         INPUT_CLOUDBEES_API_URL: ${{ cloudbees.api.url }}
         INPUT_RUN_ID: ${{ cloudbees.run_id }}
         INPUT_CLOUDBEES_EVENT_PATH: /cloudbees/event.json
         INPUT_REF: ${{ inputs.ref }}
         INPUT_WORKSPACE_DIR: ${{ inputs.workspace-dir }}